language: node_js
node_js:
- 12.12.0
cache:
  directories:
  - node_modules
script:
- npm install
- scripts/build_check.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: bIKTnTqEXYdx0MJZTp0+4L2VoFs8Cgcd/taz5pMjVSrhPtjKGBlx7pgZbHCx6TE11T+ezcRI+puNbFQKPEMIwTw0Tvn6GvBjNwDAP1YfYY09W8vZ1IAFAoIZ8kCqzJDsd17kMWA4fUBEgt8NPw0iRf7IhWYz+6IXCsFuFm+i2pcE/rxMQu5/+vMOyvLWfp5wZ4JIOsmWXtjIiRxU5M0nmtbSdaelC8no0pEt/tmlMG+UQGj7etM82rcMMlwUrhqZoFMRTTygeN5MA2tWXwquBXc4UQMi3wUeaygrmQurob4j6yUbWT7SrB1nRs+uxi4QsW3u95+b1b/Uy1lbPGcQF3DmUnveU0Nkr97F0Zg2+nLsLm10vGUK70oNbb4GhILMdek10+e0CZZJpHls+0mIJXBSapd6MpmmTcqS8hWiIKhKlmfnLMON5TnkNWlh58mKliJNGrEkiehU9wTRuDe4v9PBYSX65TxfXO2261fDtF1VPufzNWihTD4c0pRUxelRP6OctRfHnpXUZTwyML3ZjeHNGBkIgvb5AxG7wcA616K+YUss16VUfXRPaP81TRlEeOFyI42MugtlHPSp3fo0/zb6RXEPUUaByclp20zPYhvSDcBwB7DJot/xlOqwIcDYdnRv63Ji+t3B717wrkV3FyTnFe1RBGyelfIEP1BodwM=
